rdis_warehouse/rdis_warehouse/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('warehouse.urls', namespace='warehouse'), name='warehouse')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rdis_warehouse/warehouse/urls.py
from django.urls import path
from .views import logout_view, login_view, main_view, export_excel
from django.contrib import admin


app_name = 'school'

urlpatterns = [
    path('', main_view, name='main'),
    path('/admin/storage/<int:pk>/change/', admin.site.urls, name='update'),
    path('export/', export_excel, name='export_excel'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

rdis_warehouse/warehouse/models.py
from django.db import models
from django.contrib.auth.models import User


class StorageLocation(models.Model):
    id_location = models.AutoField(primary_key=True)
    location_name = models.CharField(max_length=20, verbose_name='Название расположения')

    def __str__(self):
        return self.location_name

    class Meta:
        verbose_name_plural = "Расположения хранилищ"
        verbose_name = "Расположение хранилища"


class Workers(models.Model):
    id_worker = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20, verbose_name='Имя')
    first_name = models.CharField(max_length=20, verbose_name='Фамилия')
    last_name = models.CharField(max_length=20, blank=True, null=True, verbose_name='Отчество')

    def __str__(self):
        return f"{self.first_name} {self.name} {self.last_name}"

    class Meta:
        verbose_name_plural = "Сотрудники"
        verbose_name = "Сотрудник"


class InventoryType(models.Model):
    id_type = models.AutoField(primary_key=True)
    type_name = models.CharField(max_length=50, verbose_name='Название типа инвентаря')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Ответственное лицо')

    def __str__(self):
        return self.type_name

    class Meta:
        verbose_name_plural = "Тип Инвентаря"
        verbose_name = "Тип Инвентаря"


class Inventory(models.Model):
    id_inventory = models.AutoField(primary_key=True)
    type = models.ForeignKey(InventoryType, on_delete=models.CASCADE, verbose_name='Тип инвентаря')
    inventory_name = models.CharField(max_length=50, verbose_name='Название')
    inventory_number = models.CharField(max_length=50, verbose_name='Инвентарный номер', null=True, blank=True)
    specifications = models.TextField(verbose_name='Характеристики', null=True, blank=True)
    is_active = models.BooleanField(default=True, verbose_name='Статус активности')

    def __str__(self):
        return f"{self.type} {self.inventory_name} | Номер:{self.inventory_number}"

    class Meta:
        verbose_name_plural = "Инвентарь"
        verbose_name = "Инвентарь"


class Storage(models.Model):
    id_storage = models.AutoField(primary_key=True)
    location = models.ForeignKey(StorageLocation, on_delete=models.CASCADE, verbose_name='Место нахождения')
    inventory = models.ForeignKey(Inventory, on_delete=models.CASCADE, verbose_name='Инвентарь')
    worker = models.ForeignKey(Workers, on_delete=models.CASCADE, verbose_name='Сотрудник', null=True, blank=True)

    start_date = models.DateField(null=True, verbose_name='Дата начала')
    end_date = models.DateField(null=True, verbose_name='Дата окончания', )
    comment = models.TextField(verbose_name='Комментарий', null=True, blank=True)

    def __str__(self):
        return f"{self.location} {self.inventory} {self.worker}"

    class Meta:
        verbose_name_plural = "Учеты"
        verbose_name = "Учет"

rdis_warehouse/warehouse/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .models import Storage, InventoryType, StorageLocation
from openpyxl import Workbook
from openpyxl.styles import NamedStyle, Font, Alignment
from openpyxl.styles.numbers import NumberFormat


def main_view(request):
    stuff = Storage.objects.filter(inventory__type__user=request.user.id, inventory__is_active=True)
    return render(request, 'table.html', {'stuff': stuff})


def export_excel(request):
    if request.method == 'POST':
        # Получаем количество записей, которые нужно экспортировать
        quantity = int(request.POST.get('quantity'))

        # Получаем записи из базы данных
        records = Storage.objects.filter(inventory__type__user=request.user.id,
                                         inventory__is_active=True).order_by('-id_storage')[:quantity]

        # Создаем новый Excel-файл и добавляем в него записи
        wb = Workbook()
        ws = wb.active

        ws.append(["Расположение", "Тип инвентаря",  "Название", "Инвентарный номер",
                   "Характеристики", "Закрепленный сотрудник", "Дата начала", "Дата окончания",
                   "Комментарий"])

        ws.column_dimensions['A'].width = 30
        ws.column_dimensions['B'].width = 30
        ws.column_dimensions['C'].width = 30
        ws.column_dimensions['D'].width = 30
        ws.column_dimensions['E'].width = 30
        ws.column_dimensions['F'].width = 30
        ws.column_dimensions['G'].width = 30
        ws.column_dimensions['H'].width = 30
        ws.column_dimensions['I'].width = 30

        # Устанавливаем формат ячейки для заголовков
        header_font = Font(name='Times New Roman', size=14, bold=True)
        header_alignment = Alignment(horizontal='center', vertical='center')
        for cell in ws[1]:
            cell.font = header_font
            cell.alignment = header_alignment

        for record in records:
            ws.append([record.location.location_name, record.inventory.type.type_name,
                       record.inventory.inventory_name, record.inventory.inventory_number,
                       record.inventory.specifications,
                       record.worker.first_name + " " + record.worker.name,
                       record.start_date, record.end_date, record.comment])

        #date_style = NamedStyle(name='date_style')
        #date_style.number_format = NumberFormat('dd.mm.yyyy')

        #for row in ws.iter_rows(min_row=2, max_row=len(records)+1, min_col=8, max_col=9):
        #    for cell in row:
        #        cell.style = date_style

        # Возвращаем Excel-файл в ответе на запрос
        response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
        response['Content-Disposition'] = 'attachment; filename=export.xlsx'
        wb.save(response)
        return response


def my_view(request, pk):
    storage = Storage.objects.get(pk=pk)
    return render(request, 'my_template.html', {'object': storage})


def login_view(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('warehouse:main')
        else:
            messages.error(request, "Данные не верны, пожалуйста повторите вход")
            return redirect('warehouse:login')
    else:
        return render(request, 'registration/login.html')


def logout_view(request):
    logout(request)
    messages.success(request, "Вы вышли из системы, чтобы воспользоваться сайтом войдите снова")
    return redirect('warehouse:login')

rdis_warehouse/warehouse/templates/events/breadcrumbs.html
<!-- ======= Breadcrumbs ======= -->
<section class="breadcrumbs">
  <div class="container">
    <div class="d-flex justify-content-between align-items-center">
      <h2>{{ from }}</h2>
      <ol>
        <li class="text-primary"><a class="nav-link scrollto" href="{% url 'warehouse:main'%}" >Таблицы</a></li>
        <li>{{ what }}</li>
      </ol>
    </div>
  </div>
</section>
<!-- End Breadcrumbs -->

rdis_warehouse/warehouse/templates/events/footer.html
{% load static %}
<!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="footer-top">
      <div class="container" align="center">
        <div class="row justify-content-center">
          <div class="col-lg-6">
            <h1 class="logo me-auto me-lg-0">
              <p><span>РОСДОРИФНОРМСВЯЗЬ</span></p>
            </h1>
          </div>
        </div>

      </div>
    </div>
  </footer><!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'vendor/aos/aos.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'vendor/php-email-form/validate.js' %}"></script>



  <!-- Template Main JS File -->
  <script src="{% static 'js/main.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

rdis_warehouse/warehouse/templates/events/header.html
{% load static %}

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>RDIS</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <link href="{% static 'img/logo.jpg' %}" rel="icon">
  <link href="{% static 'img/logo.jng' %}" rel="apple-touch-icon">

  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">


  <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

rdis_warehouse/warehouse/templates/events/navbar.html
{% load static %}
  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top header-inner-pages">
    <div class="container d-flex align-items-center justify-content-lg-between">

      <h1 class="logo me-auto me-lg-0">
        <a href="index.html"><span>RDIS</span></a>
        <a href="index.html"> - УЧЕТ</a>
      </h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo me-auto me-lg-0"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <nav id="navbar" class="navbar order-last order-lg-1">
        <ul>
          <li><a class="nav-link scrollto" href="{% url 'warehouse:main'%}">Таблицы</a></li>
          <li><a class="nav-link scrollto" href="#">Справочник</a></li>
          <li><a class="nav-link scrollto" target="_blank" href="{% url 'admin:index' %}">Админ панель</a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'warehouse:logout'%}">Выход</a></li>
          {% else %}
          <li><a href="{% url 'warehouse:login'%}?next={{request.path}}">Вход</a></li>
          {% endif %}
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->
    </div>
  </header><!-- End Header -->

rdis_warehouse/warehouse/templates/table.html
<!DOCTYPE html>
{% load static %}
{% csrf_token %}
<html lang="ru">

{% include "events/header.html" %}


<body>

{% include "events/navbar.html" %}

<main id="main">
  {% include "events/breadcrumbs.html" with from="Таблицы" what="" %}

  {% if user.is_authenticated %}
  <section id="profile">
    <div class="shadow-sm p-3 mb-5 bg-white rounded">
      <div class="section-title" data-aos="fade-up">
        <h2>Добро пожаловать</h2> <p>{{ user.get_username }}</p>
      </div>
    </div>


    <div class="container">
      <div class="row">
        <div class="accordion" id="accordionBasic">
          <div class="accordion-item">
            <h2 class="accordion-header" id="headingOne">
              <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                Экспортировать данные в Excel
              </button>
            </h2>
            <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionBasic">
              <div class="accordion-body">
                <form method="post" action="{% url 'warehouse:export_excel' %}">
                  {% csrf_token %}
                        <label for="quantity" class="form-label">Количество последних записей:</label>
                        <input class="form-control" type="number" id="quantity" name="quantity">
                        <button class="btn btn-success" type="submit">Экспорт в Excel</button>
                </form>
              </div>
            </div>
          </div>
        </div>


        <table class="table">
          <thead>
          <tr>
            <th>
              <a href="{% url 'admin:warehouse_storage_add' %}"><p class="text-primary">Добавить учет</p></a>
            </th>
            <th>
              <a href="{% url 'admin:warehouse_storagelocation_add' %}"><p class="text-primary">Добавить расположение</p></a>
            </th>
            <th>
              <a href="{% url 'admin:warehouse_workers_add' %}"><p class="text-primary">Добавить сотрудника</p></a>
            </th>
            <th>
              <a href="{% url 'admin:warehouse_inventory_add' %}"><p class="text-primary">Добавить инвентарь</p></a>
            </th>
            <th>
              <a href="{% url 'admin:warehouse_inventorytype_add' %}"><p class="text-primary">Добавить тип инвентаря</p></a>
            </th>
          </tr>
          </thead>
        </table>
      </div>

      <div class="row">
        <h2>Таблица учета</h2>
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th>Тип</th>
              <th>Название</th>
              <th>Инвентарный номер</th>
              <th>Место нахождения</th>
              <th>Дата выдачи</th>
              <th>Дата окончания</th>
              <th></th>
            </tr>
          </thead>

          <tbody>
          {% load admin_urls %}
          {% for item in stuff %}
          <tr>
            <td><a href="{% url 'admin:warehouse_storage_change' item.pk %}"><p class="text-primary">Изменить элемент</p></a></td>
            <td>{{ item.inventory.type }}</td>
            <td>{{ item.inventory.inventory_name }}</td>
            <td>{{ item.inventory.inventory_number }}</td>
            <td>{{ item.location }}</td>
            <td>{{ item.start_date }}</td>
            <td>{{ item.end_date }}</td>
          </tr>
          {% endfor %}
          </tbody>
        </table>

      </div>
    </div>

  </section>

  {% else %}
  <section id="not authenticated">
    <div class="shadow-sm p-3 mb-5 bg-white rounded">
      <div class="section-title" data-aos="fade-up">
        <h2>Вы не авторизованы</h2> <p><a href="{% url 'warehouse:login'%}?next={{request.path}}">Войти в систему</a></p>
      </div>
    </div>
  </section>

  {% endif %}
</main>


{% include "events/footer.html" %}

</body>

</html>

rdis_warehouse/warehouse/templates/update.html
<!DOCTYPE html>
{% load static %}
{% csrf_token %}
<html lang="ru">

{% include "events/header.html" %}


<body>

{% include "events/navbar.html" %}

<main id="main">
  {% include "events/breadcrumbs.html" with from="Таблицы" what="Изменение элемента" %}

  <section id="profile">
    <div class="shadow-sm p-3 mb-5 bg-white rounded">
      <div class="section-title" data-aos="fade-up">
        <h2>Добро пожаловать</h2> <p>{{ user.get_username }}</p>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <h2>Таблица учета</h2>
        <table class="table">
          <thead>
            <tr>
              <th>Тип</th>
              <th>Название</th>
              <th>Инвентарный номер</th>
              <th>Место нахождения</th>
              <th>Дата выдачи</th>
              <th>Дата окончания</th>
              <th></th>
            </tr>
          </thead>

          <tbody>
          <tr>
            <td>
              <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButtonOne" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{ item.inventory.type }}
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButtonOne">
                  {% for type in type_inventory %}
                  <a class="dropdown-item" href="#" name="product" value="{{ type.id_type }}" onclick="updateDropdownText(event, 'dropdownMenuButtonOne')">{{ type.type_name }}</a>
                  {% endfor %}
                </div>
              </div>
            </td>
            <td>
              <input type="text" class="form-control" value="{{ item.inventory.inventory_name }}" data-id="{{ item.inventory.id_inventory }}">
            </td>
            <td>
              <input type="text" class="form-control" value="{{ item.inventory.inventory_number }}" data-id="{{ item.inventory.id_inventory }}">
            </td>

            <td>
              <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButtonTwo" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{ item.location }}
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButtonTwo">
                  {% for location in locations %}
                  <a class="dropdown-item" href="#" name="location" value="{{ location.id_location }}" onclick="updateDropdownText(event, 'dropdownMenuButtonTwo')">{{ location.location_name }}</a>
                  {% endfor %}
                </div>
              </div>
            </td>

            <td>
<div class="input-append date" id="dp3" data-date="12-02-2012" data-date-format="dd-mm-yyyy">
  <input class="span2" size="16" type="text" value="12-02-2012">
  <span class="add-on"><i class="icon-th"></i></span>
</div>
            </td>

            <td>{{ item.end_date }}</td>
          </tr>
          </tbody>
        </table>

      </div>
    </div>

  </section>
</main>



</body>

{% include "events/footer.html" %}

<script>
function updateDropdownText(event, dropdownId) {
  event.preventDefault();
  const selectedText = event.target.textContent;
  const dropdownButton = document.getElementById(dropdownId);
  dropdownButton.textContent = selectedText;
}

</script>

</html>